---
title: "NFL Special Teams EDA"
author: "Jordan K. Fiegl"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading Packages

```{r load libraries, warning=FALSE, message=FALSE}
library(here)
library(janitor)
library(broom)
library(Hmisc)
library(tidyverse)
```

# Reading in Data

## Loading player data

```{r player data}
players_raw <- read_csv(here("data/players.csv")) %>% 
  clean_names()

players_raw
```


## Loading game data

```{r game data}
games_raw <- read_csv(here("data/games.csv")) %>% clean_names()

games_raw %>% head()
```

## Loading plays data

```{r plays data}
plays_raw <- read_csv(here("data/plays.csv")) %>% clean_names()

plays_raw %>% head()
```

## Loading PFF Scouting Data

```{r PFF data}
pff_raw <- read_csv(here("data/PFFScoutingData.csv")) %>% clean_names()

pff_raw %>% head()

```

##  Loading tracking 2018

```{r 2018 tracking data}
track18_raw <- read_csv(here("data/tracking2018.csv")) %>% clean_names()

track18_raw %>% head()
```




##  Loading tracking 2019

```{r 2019 tracking data}
track19_raw <- read_csv(here("data/tracking2019.csv")) %>% clean_names()

track19_raw %>% head()
```


##  Loading tracking 2020

```{r 2020 tracking data}
track20_raw <- read_csv(here("data/tracking2020.csv")) %>% clean_names()

track20_raw %>% head()
```



# Data Cleaning

## Taking closer look at datasets

### Players

```{r examine players data}
players_raw %>% describe()
```

### Games

```{r examine games data}
games_raw %>% describe()
```

### PLays


```{r examine plays data}
plays_raw %>% describe()
```

### PFF Scouting

```{r}
pff_raw %>% describe()
```
































## Session Info

```{r}
sessioninfo::session_info()
```



